"""add about

Revision ID: 72cbcbd8a6cb
Revises: 67faace3e465
Create Date: 2025-05-30 19:04:12.840649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlmodel import AutoString

# revision identifiers, used by Alembic.
revision: str = "72cbcbd8a6cb"
down_revision: Union[str, None] = "67faace3e465"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("about")
    # ### end Alembic commands ###
